### ISSUE TITLE
[Feature request] Does it render immediately if debounce props is 0 ?

### ISSUE THREAD

**Issue by ambroiseRabier** [Rebsos/react-debounce-component#4]
When a setTimeout is called, it always wait at least one frame, event if delay is 0.
For example I have a debounce function I have found on stackoverflow, and modified so that it call the function it debounce immediately if the delay is set to 0:

```ts
export function debounce(func: (e: any) => void, delay: number): (event?: any) => void {
  let timerID: number;
  return function(event?: any) {
    // needed for testing in jest.
    if (!!event && !!event.persist) {
      event.persist();
    }

    if (delay <= 0) { // <-- this, skip the setTimeout to not have one frame delay
      func(event)
    }

    if (timerID) {
      clearTimeout(timerID);
    }
    timerID = setTimeout(func, delay, event);
  };
}
```

I haven't tested yet, but by looking at the code, it seem there is no skip `setTimeout` feature. Can you confirm ? And would you mind implementing it if you think it is feasible?

**Comment by Rebsos** [comment]
I have to test it.
What about this for now?
`delay === 0 ? <List/> : <Debounce ms={delay}><List/></Debounce>`

**Comment by ambroiseRabier** [comment]
Oh indeed, that's simple, how did I miss it !

**Comment by Rebsos** [comment]
Good to hear :)
I'll close this for now.
